// Copyright (c) 2026 xiayu
// Contact: 126240622+xiayu1987@users.noreply.github.com
// SPDX-License-Identifier: MIT

import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { readFileSync } from 'node:fs'
const en=JSON.parse(readFileSync(new URL('../../locales/en.json',import.meta.url),'utf8'))
test.use({locale:'zh-CN'})
test('embedded console manages real Go API and streams model output', async ({ page }) => {
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto(process.env.NOOBLOFT_TEST_URL!)
  await page.getByRole('combobox',{name:'语言 / Language'}).selectOption('en')
  await expect(page.getByRole('button',{name:en['login.submit'],exact:true})).toBeVisible()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang','en')
  await page.getByPlaceholder(en['login.placeholder']).fill('invalid')
  await page.getByRole('button',{name:en['login.submit'],exact:true}).click()
  await expect(page.getByText('管理凭证无效',{exact:true})).toHaveCount(0)
  await page.getByRole('combobox',{name:'语言 / Language'}).selectOption('zh-CN')
  await page.getByPlaceholder('输入管理凭证').fill('invalid')
  await page.getByRole('button',{name:'登录控制台'}).click()
  await expect(page.getByText('管理凭证无效')).toBeVisible()
  await page.getByPlaceholder('输入管理凭证').fill(process.env.NOOBLOFT_TEST_TOKEN!)
  await page.getByRole('button',{name:'登录控制台'}).click()
  await expect(page.getByRole('heading',{name:'节点概览'})).toBeVisible()
  await page.getByRole('menuitem',{name:'我的发布服务'}).click()
  await expect(page.locator('[data-test="authorization-status"]')).toBeVisible()
  const findings = page.locator('.finding')
  await expect(findings.first()).toBeVisible()
  await expect(findings.first().locator('.el-tag').nth(1)).not.toBeEmpty()
  const assistantDrawer = page.getByRole('dialog',{name:'签发命令助手'})
  await page.getByRole('button',{name:'签发命令助手',exact:true}).click()
  await expect(assistantDrawer).toBeVisible()
  await expect(assistantDrawer).toHaveClass(/rtl/)
  await expect.poll(async () => (await assistantDrawer.boundingBox())!.width).toBeGreaterThan(900)
  await assistantDrawer.getByLabel('根身份目录（-root，必录）').fill('D:\\publisher-root')
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('publisher service')
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('-root D:\\publisher-root')
  await expect(assistantDrawer.getByText('输出文件（-file，必录，默认 根身份目录下的 service.noobloft / consumer-access.json / revocations-1.json）').first()).toBeVisible()
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('-file D:\\publisher-root\\service.noobloft')
  await expect(assistantDrawer.getByText('有效期（-ttl，必录，默认 24h）').first()).toBeVisible()
  await expect(assistantDrawer.getByText('连接地址（-addresses，选填，默认 本节点 network.announceAddrs + /p2p/PeerID）').first()).toBeVisible()
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('-addresses /ip4/127.0.0.1/tcp/4001/p2p/consumer')
  await assistantDrawer.getByText('消费凭证',{exact:true}).click()
  await expect(assistantDrawer.getByText('每分钟请求上限（-rpm，必录，默认 30）').first()).toBeVisible()
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('-max-tokens 1024 -concurrency 1 -rpm 30')
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('-file D:\\publisher-root\\consumer-access.json')
  await assistantDrawer.getByText('吊销快照',{exact:true}).click()
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('publisher revocations')
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('-file D:\\publisher-root\\revocations-1.json')
  await assistantDrawer.getByRole('button',{name:'关闭',exact:true}).click()
  await expect(assistantDrawer).not.toBeVisible()
  await page.getByRole('button',{name:'导出服务描述',exact:true}).click()
  const exportDrawer = page.getByRole('dialog',{name:'导出发布者服务描述'})
  await expect(exportDrawer).toBeVisible()
  await expect(exportDrawer).toHaveClass(/rtl/)
  await expect.poll(async () => (await exportDrawer.boundingBox())!.width).toBeGreaterThan(900)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button',{name:'下载 service.noobloft'}).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('service.noobloft')
  const serviceText = await readFile((await download.path())!, 'utf8')
  const service = JSON.parse(serviceText)
  expect(service.kind).toBe('service')
  expect(service.signature).toBeTruthy()
  expect(serviceText).not.toContain('backend-test-secret')
  await page.setViewportSize({width:390,height:844})
  await expect.poll(async () => Math.round((await exportDrawer.boundingBox())!.width)).toBe(390)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await exportDrawer.getByRole('button',{name:'关闭',exact:true}).click()
  await page.setViewportSize({width:1280,height:720})
  await page.getByRole('button',{name:'安装服务委托',exact:true}).click()
  const installDrawer = page.getByRole('dialog',{name:'安装发布服务'})
  await expect(installDrawer).toBeVisible()
  await expect(installDrawer.getByText('签名吊销快照（必录）')).toBeVisible()
  await expect(installDrawer.locator('[data-test="revocations-hint"]')).toContainText('publisher revocations')
  await expect(installDrawer.locator('[data-test="import-guide"]')).toContainText('-peers 必须包含本节点 PeerID')
  await expect(installDrawer.getByRole('button',{name:'打开签发命令助手：吊销快照'})).toBeVisible()
  await installDrawer.locator('input.el-input__inner').fill(service.publisher)
  await installDrawer.getByPlaceholder('粘贴签名文档或选择文件').fill(serviceText)
  await expect(installDrawer.locator('[data-test="publisher-compare"]')).toContainText('与填写的 ID 一致')
  await expect(installDrawer.getByRole('button',{name:'验证并保存'})).toBeDisabled()
  await installDrawer.getByPlaceholder('粘贴签名吊销快照或选择文件').fill('{')
  await installDrawer.getByRole('button',{name:'验证并保存'}).click()
  await expect(page.getByText('签名吊销快照不是合法 JSON',{exact:false})).toBeVisible()
  await installDrawer.locator('.el-drawer__close-btn').click()
  await expect(installDrawer).not.toBeVisible()
  await page.getByRole('button',{name:'安装服务委托',exact:true}).click()
  await installDrawer.getByRole('button',{name:'打开签发命令助手：吊销快照'}).click()
  await expect(assistantDrawer.locator('[data-test="assistant-command"]')).toContainText('publisher revocations')
  await assistantDrawer.getByRole('button',{name:'关闭',exact:true}).click()
  await installDrawer.locator('.el-drawer__close-btn').click()
  await expect(installDrawer).not.toBeVisible()
  await expect(page).toHaveURL(/#\/publisher$/)
  await page.reload()
  await expect(page.getByRole('heading',{name:'我的发布服务'})).toBeVisible()
  await expect(page.getByRole('button',{name:'登录控制台'})).toHaveCount(0)
  expect(await page.evaluate(()=>document.cookie)).toBe('')
  const session=(await page.context().cookies()).find(c=>c.name==='noobloft_session')
  expect(session?.httpOnly).toBe(true)
  expect(session?.sameSite).toBe('Strict')
  await page.getByRole('button',{name:'启用本机在线签发',exact:true}).click()
  await page.getByRole('button',{name:'确定',exact:true}).click()
  await page.getByRole('button',{name:'签发消费凭证',exact:true}).click()
  const issueDrawer=page.getByRole('dialog',{name:'签发消费凭证',exact:true})
  await expect(issueDrawer).toHaveClass(/rtl/)
  await issueDrawer.getByLabel('消费者 PeerID（必填）').fill(service.peers[0])
  await issueDrawer.getByRole('button',{name:'签发并保存记录'}).click()
  await expect(issueDrawer).not.toBeVisible()
  const issuedRow=page.getByRole('row').filter({has:page.getByRole('button',{name:'吊销',exact:true})})
  await expect(issuedRow).toHaveCount(1)
  await issuedRow.getByRole('button',{name:'吊销',exact:true}).click()
  await page.getByRole('button',{name:'确定',exact:true}).click()
  await expect(issuedRow).toContainText('已吊销')
  await page.reload()
  await expect(issuedRow).toContainText('已吊销')
  await expect(issuedRow.getByRole('button',{name:'吊销',exact:true})).toBeDisabled()
  await page.getByRole('menuitem',{name:'微网络订阅'}).click()
  await page.getByRole('button',{name:'添加订阅'}).click()
  await expect(page.getByRole('heading',{name:'导入服务订阅'})).toBeVisible()
  await expect(page.getByRole('dialog',{name:'导入服务订阅'})).toHaveClass(/rtl/)
  await expect.poll(async () => (await page.getByRole('dialog',{name:'导入服务订阅'}).boundingBox())!.width).toBeGreaterThan(900)
  await page.getByRole('dialog',{name:'导入服务订阅'}).locator('input.el-input__inner').fill(service.publisher)
  await page.getByPlaceholder('粘贴签名文档或选择文件').fill(serviceText)
  await page.getByRole('button',{name:'验证并保存'}).click()
  await expect(page.getByRole('dialog',{name:'导入服务订阅'})).not.toBeVisible()
  await expect(page.getByText(service.publisher,{exact:true})).toBeVisible()
  await page.getByRole('menuitem',{name:'节点配置'}).click()
  await page.getByRole('button',{name:'编辑配置'}).click()
  await page.getByRole('spinbutton').fill('7')
  await page.getByRole('button',{name:'保存配置',exact:true}).click()
  await expect(page.getByText('有已保存但尚未生效的配置', {exact:false})).toBeVisible()
  await page.getByRole('menuitem',{name:'模型与调试'}).click()
  await page.getByRole('combobox').filter({hasNot:page.locator('option')}).click()
  await page.getByRole('option',{name:'test-model'}).click()
  await page.locator('textarea').fill('hello')
  await page.getByRole('button',{name:'发送',exact:true}).click()
  await expect(page.locator('.response')).toHaveText('浏览器流式测试成功')
  await page.getByRole('menuitem',{name:'资源管理与使用说明'}).click()
  await expect(page.getByRole('heading',{name:'功能与操作说明（Windows / Linux）'})).toBeVisible()
  await expect(page.getByText('签发历史事实源；安装关系由保存与运行配置派生',{exact:true})).toBeVisible()
  const englishResources=page.waitForResponse(r=>r.url().endsWith('/manage/resources')&&r.request().headers()['accept-language']==='en')
  await page.getByRole('combobox',{name:'语言 / Language'}).selectOption('en')
  expect((await englishResources).ok()).toBe(true)
  await expect(page.getByRole('heading',{name:en['nav.resources'],exact:true})).toBeVisible()
  await expect(page.getByText('签发历史事实源；安装关系由保存与运行配置派生',{exact:true})).toHaveCount(0)
  await page.getByRole('combobox',{name:'语言 / Language'}).selectOption('zh-CN')
  await page.getByRole('button',{name:'恢复初始配置',exact:true}).click()
  const resetDrawer=page.getByRole('dialog',{name:'恢复初始配置：确认范围'})
  await expect(resetDrawer).toHaveClass(/rtl/)
  await expect(resetDrawer.getByRole('button',{name:'备份、恢复并重启'})).toBeDisabled()
  await resetDrawer.getByLabel('必填：输入 RESET CONFIG').fill('RESET CONFIG')
  await resetDrawer.getByRole('button',{name:'备份、恢复并重启'}).click()
  await expect(resetDrawer).not.toBeVisible()
  await expect(page.getByText(/最近操作 .*恢复完成，节点已启动/)).toBeVisible()
  await page.getByRole('menuitem',{name:'我的发布服务'}).click()
  await expect(issuedRow).toContainText('已吊销')
  await page.getByRole('menuitem',{name:'微网络订阅'}).click()
  await expect(page.getByText('尚未订阅发布者',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'退出',exact:true}).click()
  await expect(page.getByRole('button',{name:'登录控制台'})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button',{name:'登录控制台'})).toBeVisible()
  expect((await page.context().cookies()).find(c=>c.name==='noobloft_session')).toBeUndefined()
  expect(await page.evaluate(()=>Object.keys(localStorage))).toEqual(['noobloft.language'])
  expect(await page.evaluate(()=>Object.keys(sessionStorage))).toEqual([])
  expect(errors).toEqual([])
})
