#!/usr/bin/env sh
# Copyright (c) 2026 xiayu
# Contact: 126240622+xiayu1987@users.noreply.github.com
# SPDX-License-Identifier: MIT

set -eu
swarm_lang=zh-CN
for v in "${NOOBLOFT_LANG:-}" "${LC_ALL:-}" "${LC_MESSAGES:-}" "${LANG:-}"; do
    [ -n "$v" ] || continue
    case $(printf '%s' "$v" | tr 'A-Z' 'a-z') in en|en[-_.]*) swarm_lang=en ;; *) swarm_lang=zh-CN ;; esac
    break
done
t() { if [ "$swarm_lang" = en ]; then printf '%s' "$2"; else printf '%s' "$1"; fi; }
for arg in "$@"; do
    case $arg in -h|--help)
        echo "$(t '用法: sh scripts/start.sh [--mode private|shared] [--dir 节点目录] [--user 服务用户] [-- init参数]' 'Usage: sh scripts/start.sh [--mode private|shared] [--dir node-dir] [--user service-user] [-- init-args]')"
        echo "$(t '流程: 按需构建 -> 安装 -> 仅首次初始化 -> systemd 启动 -> 管理台登录。' 'Flow: build if needed -> install -> initialise on first run only -> start via systemd -> sign in to the console.')"
        echo "$(t '--mode 选填默认 private；shared 使用发布者授权；已有目录保留保存模式。' '--mode is optional, default private; shared uses publisher authorisation; existing directories keep their saved mode.')"
        echo "$(t '--dir 默认调用者 ~/.noobloft；--user 默认调用者。启动后使用节点目录 admin.token 登录。' '--dir defaults to the caller ~/.noobloft; --user defaults to the caller. Sign in with admin.token from the node directory.')"
        echo "$(t '完整在线管理说明: noobloftd manage help；页面入口: 资源管理与使用说明。' 'Full management guide: noobloftd manage help; console page: Resources and usage.')"
        echo "$(t '输出语言：设置 NOOBLOFT_LANG=en 或 zh-CN。' 'Output language: set NOOBLOFT_LANG=en or zh-CN.')"
        exit 0 ;;
    esac
done

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
service=noobloft
unit_path=/etc/systemd/system/$service.service
install_dir=/usr/local/lib/noobloft
installed_bin=$install_dir/noobloftd
built_bin=$repo_dir/bin/noobloftd

if [ "$(id -u)" -ne 0 ]; then
    exec sudo -- env NOOBLOFT_LANG="$swarm_lang" sh "$0" "$@"
fi

run_user=${SUDO_USER:-root}
node_dir=
init_mode=private
while [ $# -gt 0 ]; do
    case $1 in
        --dir) node_dir=$2; shift 2 ;;
        --user) run_user=$2; shift 2 ;;
        --mode) init_mode=$2; shift 2 ;;
        --) shift; break ;;
        *) echo "$(t "未知参数: $1（init 参数请放在 -- 之后）" "Unknown argument: $1 (put init arguments after --)")" >&2; exit 2 ;;
    esac
done
case $init_mode in private|shared) ;; *) echo "$(t '--mode 必须为 private 或 shared' '--mode must be private or shared')" >&2; exit 2 ;; esac

run_home=$(getent passwd "$run_user" | cut -d: -f6)
if [ -z "$run_home" ]; then
    echo "$(t "服务用户不存在: $run_user" "Service user does not exist: $run_user")" >&2
    exit 1
fi
[ -n "$node_dir" ] || node_dir=$run_home/.noobloft
case $node_dir in /*) ;; *) node_dir=$(pwd)/$node_dir ;; esac

as_user() {
    if [ "$run_user" = root ]; then "$@"; else runuser -u "$run_user" -- "$@"; fi
}

stale() {
    [ -x "$built_bin" ] || return 0
    for p in cmd internal locales web/src web/index.html web/package.json web/package-lock.json go.mod go.sum; do
        [ -e "$repo_dir/$p" ] || continue
        if [ -n "$(find "$repo_dir/$p" -type f -newer "$built_bin" ! -path '*/internal/controlplane/webui/dist/*' -print 2>/dev/null | head -n 1)" ]; then
            return 0
        fi
    done
    return 1
}
if stale; then
    echo "$(t '== 构建（二进制缺失或比源码旧）' '== Build (binary missing or older than sources)')"
    for tool in go npm; do
        if ! command -v "$tool" >/dev/null 2>&1; then
            echo "$(t "需要构建，但本机没有 $tool。请安装 Go 和 Node.js，或在其他机器上构建好 bin/noobloftd 后复制过来。" "A build is needed but $tool is not installed. Install Go and Node.js, or build bin/noobloftd elsewhere and copy it here.")" >&2
            exit 1
        fi
    done
    if [ -n "${SUDO_USER:-}" ]; then runuser -u "$SUDO_USER" -- sh "$repo_dir/scripts/build.sh"; else sh "$repo_dir/scripts/build.sh"; fi
else
    echo "$(t '== 构建：二进制已是最新，跳过' '== Build: binary up to date, skipped')"
fi

changed=0
if cmp -s "$built_bin" "$installed_bin"; then
    echo "$(t "== 安装：$installed_bin 已是最新" "== Install: $installed_bin up to date")"
else
    echo "$(t "== 安装到 $installed_bin" "== Installing to $installed_bin")"
    install -d -m 0755 "$install_dir"
    install -m 0755 "$built_bin" "$installed_bin.new"
    mv -f "$installed_bin.new" "$installed_bin"
    changed=1
fi

if [ -f "$node_dir/config.json" ]; then
    echo "$(t "== 初始化：已存在 $node_dir/config.json，跳过" "== Init: $node_dir/config.json exists, skipped")"
else
    echo "$(t "== 初始化节点目录 $node_dir（用户 $run_user）" "== Initialising node directory $node_dir (user $run_user)")"
    as_user "$installed_bin" init -dir "$node_dir" -mode "$init_mode" "$@"
fi

unit_node_dir=$(printf '%s' "$node_dir" | sed 's/\\/\\\\/g; s/"/\\"/g; s/%/%%/g; s/\$/$$/g')
unit_tmp=$(mktemp)
trap 'rm -f "$unit_tmp"' EXIT
cat >"$unit_tmp" <<EOF
# Generated by $repo_dir/scripts/start.sh; rerunning it overwrites manual edits.
[Unit]
Description=Noobloft node ($node_dir)
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=$run_user
ExecStart=$installed_bin run -dir "$unit_node_dir"
Restart=on-failure
RestartSec=5
TimeoutStopSec=20
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
if cmp -s "$unit_tmp" "$unit_path"; then
    echo "$(t "== 服务：$unit_path 未变化" "== Service: $unit_path unchanged")"
else
    echo "$(t "== 服务：写入 $unit_path" "== Service: writing $unit_path")"
    install -m 0644 "$unit_tmp" "$unit_path"
    systemctl daemon-reload
    changed=1
fi

systemctl is-enabled --quiet "$service" 2>/dev/null || systemctl enable --quiet "$service"
restarts_before=$(systemctl show -p NRestarts --value "$service" 2>/dev/null || echo 0)
if systemctl is-active --quiet "$service"; then
    if [ "$changed" = 1 ]; then
        echo "$(t '== 二进制或 unit 有变化，重启服务' '== Binary or unit changed, restarting service')"
        systemctl restart "$service"
    else
        echo "$(t '== 服务已在运行，无变化，不重启' '== Service already running and unchanged, not restarting')"
    fi
else
    echo "$(t '== 启动服务' '== Starting service')"
    systemctl start "$service"
fi

sleep 3
restarts_after=$(systemctl show -p NRestarts --value "$service" 2>/dev/null || echo 0)
if ! systemctl is-active --quiet "$service" || [ "${restarts_after:-0}" -gt "${restarts_before:-0}" ]; then
    restarts=$((${restarts_after:-0} - ${restarts_before:-0}))
    echo "$(t "服务未能稳定运行（3 秒内自动重启 $restarts 次），最近日志：" "Service is not running stably ($restarts automatic restarts within 3s); recent log:")" >&2
    journalctl -u "$service" -n 30 --no-pager >&2 || true
    exit 1
fi

bind=$(sed -n 's/.*"bindAddr"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$node_dir/config.json" | head -n 1)
echo
echo "$(t "节点目录: $node_dir（服务用户 $run_user）" "Node dir: $node_dir (service user $run_user)")"
[ -n "$bind" ] && echo "$(t "管理台  : http://$bind/ （登录凭证: $node_dir/admin.token）" "Console : http://$bind/ (sign-in token: $node_dir/admin.token)")"
echo "$(t "管理    : systemctl status|restart|stop $service    日志: journalctl -u $service -f" "Manage  : systemctl status|restart|stop $service    Log: journalctl -u $service -f")"
