<!--
Copyright (c) 2026 xiayu
Contact: 126240622+xiayu1987@users.noreply.github.com
SPDX-License-Identifier: MIT
-->

<script setup lang="ts">
import { t, locale } from './i18n/index'

import { ref, computed, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, streamChat } from './api/client'
import SettingsForm from './features/settings/SettingsForm.vue'
import ServiceExport from './features/authorization/ServiceExport.vue'
import AuthorizationStatus from './features/authorization/AuthorizationStatus.vue'
import IssuerPanel from './features/issuer/IssuerPanel.vue'
import ResourcesPanel from './features/resources/ResourcesPanel.vue'
import LanguageSelect from './components/LanguageSelect.vue'
const authenticated=ref(false), checking=ref(true), password=ref(''), busy=ref(false), state=ref<any>(null), page=ref('overview')
const models=ref<any[]>([]), peers=ref<any[]>([]), drawer=ref(''), operation=ref('subscribe'), trust=ref(''), documentText=ref(''), revocationsText=ref('')
const model=ref(''), prompt=ref(''), answer=ref(''), reasoning=ref(''), streaming=ref(false)
let abort: AbortController | undefined
const titles = computed<Record<string,string>>(() => ({overview:t('nav.overview'),subscriptions:t('nav.subscriptions'),publisher:t('nav.publisher'),models:t('nav.models'),peers:t('nav.peers'),settings:t('nav.settings'),resources:t('nav.resources')}))
function pageFromHash(){const key=decodeURIComponent(location.hash.replace(/^#\/?/,''));return key in titles.value?key:'overview'}
page.value=pageFromHash()
window.addEventListener('hashchange',()=>{const key=pageFromHash();if(key!==page.value){if(authenticated.value)navigate(key);else page.value=key}})
refresh().then(enter,()=>{}).finally(()=>{checking.value=false})
const subscriptions=computed(()=>state.value?.saved.subscriptions || [])
const date=(n:number)=>n?new Date(n*1000).toLocaleString(locale.value):'—'
async function refresh(){state.value=await api('state')}
watch(locale, ()=>{if(authenticated.value)void refresh().catch(e=>ElMessage.error(e.message))})
async function enter(){authenticated.value=true;if(page.value==='models'||page.value==='peers')await navigate(page.value)}
async function login(){busy.value=true;try{await api('session','POST',{token:password.value.trim()});await refresh();password.value=''}catch(e:any){ElMessage.error(e.message);return}finally{busy.value=false}await enter()}
async function logout(){abort?.abort();try{await api('session','DELETE')}catch(e:any){ElMessage.error(e.message)}authenticated.value=false;state.value=null;models.value=[];peers.value=[];answer.value='';reasoning.value='';documentText.value='';revocationsText.value='';drawer.value=''}
async function navigate(key:string){page.value=key;if(pageFromHash()!==key||!location.hash)location.hash='#/'+key;busy.value=true;try{await refresh();if(key==='models')models.value=(await api('models')).data||[];if(key==='peers')peers.value=(await api('peers')).peers||[]}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
function openImport(op:string,publisher=''){operation.value=op;trust.value=publisher;documentText.value='';revocationsText.value='';drawer.value='import'}
async function readDocument(event:Event,target:string){const input=event.target as HTMLInputElement;const f=input.files?.[0];if(!f)return;if(f.size>65536){ElMessage.error(t('import.fileTooLarge'));return}const text=await f.text();if(target==='revocations')revocationsText.value=text;else documentText.value=text;input.value=''}
async function mutate(path:string,method:string,body:unknown){busy.value=true;try{const result=await api(path,method,body,state.value.revision);await refresh();drawer.value='';ElMessage.success(result.applied?t('import.revocationsApplied'):t('config.savedRestartRequired'))}catch(e:any){ElMessage.error(e.message)}finally{busy.value=false}}
const needsRevocations=computed(()=>operation.value==='install')
const canImport=computed(()=>!!trust.value.trim()&&!!documentText.value.trim()&&(!needsRevocations.value||!!revocationsText.value.trim()))
function parseDocument(text:string,name:string){if(!text.trim())throw new Error(name+t('validation.empty'));try{return JSON.parse(text)}catch(e:any){throw new Error(name+t('validation.invalidJson')+e.message)}}
const authStatus=ref<any>(null)
const ISSUE_LABEL = computed<Record<string,string>>(() => ({service:t('signing.openService'),revocations:t('signing.openRevocations')}))
const TRUST_HINT = computed(() => (t('import.trustHint')))
const guide=computed(()=>{const self=state.value?.peerId||t('node.selfPeerId');return ({
 install:{title:t('import.installTitle'),intro:t('import.installIntro'),steps:[t('import.installSignStep')+self+t('import.installPeerRequired'),t('import.installRevocationsStep'),t('import.installFilesStep'),t('config.restartAfterSaving')],issue:['service','revocations'],documentLabel:t('import.serviceFile'),document:t('import.serviceFileHint')},
 subscribe:{title:t('import.subscribeTitle'),intro:t('import.subscribeIntro'),steps:[t('import.obtainServiceStep'),t('import.subscribeFileStep'),t('import.obtainCredentialStep'),t('config.restartAfterSaving')],issue:[],documentLabel:t('import.serviceFile'),document:t('import.publisherServiceHint')},
 credential:{title:t('import.credentialTitle'),intro:t('import.credentialIntro'),steps:[t('import.sharePeerIdStep')+self+t('common.period'),t('import.issueCredentialStep'),t('import.credentialFileStep')],issue:[],documentLabel:t('import.credentialFile'),document:t('import.credentialFileHint')},
 'apply-revocations':{title:t('import.revocationsTitle'),intro:t('import.revocationsIntro'),steps:[t('import.renewRevocationsStep'),t('import.revocationsFileStep')],issue:['revocations'],documentLabel:t('import.newRevocationsFile'),document:t('import.revocationsFileHint')}
} as Record<string,any>)[operation.value]})
const docPublisher=computed(()=>{try{return JSON.parse(documentText.value)?.publisher||''}catch{return ''}})
async function importDocument(){let document,revocations;try{document=parseDocument(documentText.value,t('import.signedDocument'));if(needsRevocations.value)revocations=parseDocument(revocationsText.value,t('import.signedRevocations'))}catch(e:any){ElMessage.error(e.message);return}await mutate('publisher','POST',{operation:operation.value,trust:trust.value.trim(),document,revocations})}
async function removeSubscription(id:string){try{await ElMessageBox.confirm(t('subscription.removeConfirm'),t('subscription.remove'),{type:'warning'});await mutate('subscription','DELETE',{publisher:id})}catch{}}
async function chat(){if(!model.value||!prompt.value.trim())return;streaming.value=true;answer.value='';reasoning.value='';abort=new AbortController();try{await streamChat({model:model.value,messages:[{role:'user',content:prompt.value}],stream:true,max_tokens:256},abort.signal,(text,r)=>{answer.value+=text;reasoning.value+=r})}catch(e:any){if(e.name!=='AbortError')ElMessage.error(e.message)}finally{streaming.value=false}}
</script>
<template>
  <LanguageSelect />
  <main v-if="checking" class="login" v-loading="true"></main>
  <main v-else-if="!authenticated" class="login"><el-card class="login-card"><div class="brand">NOOBLOFT <span>{{ t('app.console') }}</span></div><h1>{{ t('login.heading') }}</h1><p class="muted">{{ t('login.sessionHint') }}</p><el-form @submit.prevent="login"><el-form-item :label="t('login.credential')"><el-input v-model="password" type="password" show-password autocomplete="off" :placeholder="t('login.placeholder')" /></el-form-item><el-button type="primary" native-type="submit" :loading="busy" :disabled="!password.trim()">{{ t('login.submit') }}</el-button></el-form></el-card></main>
  <el-container v-else class="shell"><el-aside width="220px"><div class="brand">NOOBLOFT</div><div class="subtitle">{{ t('app.subtitle') }}</div><el-menu :default-active="page" @select="navigate"><el-menu-item v-for="(title,key) in titles" :key="key" :index="key">{{title}}</el-menu-item></el-menu><div class="sidebar-footer">{{ t('login.cookieHint') }}</div></el-aside><el-container><el-header><h2>{{titles[page]}}</h2><div><el-button :loading="busy" @click="navigate(page)">{{ t('common.refresh') }}</el-button><el-button @click="logout">{{ t('login.signOut') }}</el-button></div></el-header><el-main v-loading="busy">
  <el-alert v-if="state?.pendingRestart" :title="t('config.pendingNotice')" type="warning" :closable="false" class="notice" />
  <template v-if="state">
  <ResourcesPanel v-if="page==='resources'" :state="state" @changed="refresh" />
  <ServiceExport v-if="page==='publisher'" :state="state" />
  <IssuerPanel v-if="page==='publisher'" :state="state" @changed="refresh" />
  <AuthorizationStatus ref="authStatus" v-if="page==='publisher'" :state="state" @navigate="navigate" />
  <section v-if="page==='overview'"><div class="stats"><el-card><span>{{ t('overview.networkMode') }}</span><strong>{{state.running.network.mode}}</strong></el-card><el-card><span>{{ t('subscription.savedCount') }}</span><strong>{{subscriptions.length}}</strong></el-card><el-card><span>{{ t('overview.runningService') }}</span><strong>{{state.running.provider.enabled?t('common.enabled'):t('common.disabled')}}</strong></el-card></div><el-card class="spaced"><h3>{{ t('overview.currentNode') }}</h3><el-descriptions :column="1" border><el-descriptions-item label="PeerID"><code>{{state.peerId}}</code></el-descriptions-item><el-descriptions-item :label="t('overview.startedAt')">{{date(state.startedAt)}}</el-descriptions-item><el-descriptions-item :label="t('overview.gateway')">{{state.running.gateway.bindAddr}}</el-descriptions-item><el-descriptions-item :label="t('config.status')">{{state.pendingRestart?t('config.pendingRestart'):t('config.applied')}}</el-descriptions-item></el-descriptions></el-card></section>
  <section v-if="page==='subscriptions'"><div class="toolbar"><p>{{ t('subscription.isolationHint') }}</p><el-button type="primary" @click="openImport('subscribe')">{{ t('subscription.add') }}</el-button></div><el-empty v-if="!subscriptions.length" :description="t('subscription.empty')"/><el-card v-for="sub in subscriptions" :key="sub.service.publisher" class="spaced"><div class="toolbar"><h3>{{ t('subscription.publisherNetwork') }}</h3><el-tag :type="sub.access && sub.access.expiresAt*1000>Date.now()?'success':'warning'">{{sub.access?t('subscription.credentialExpires')+date(sub.access.expiresAt):t('subscription.credentialMissing')}}</el-tag></div><p class="mono">{{sub.service.publisher}}</p><p>{{ t('subscription.serviceExpires') }}{{date(sub.service.expiresAt)}}</p><el-tag v-for="name in sub.service.models" :key="name" class="model-tag">{{name}}</el-tag><p v-if="sub.access">{{ t('subscription.allowedModels') }}{{sub.access.models?.join(t('common.listSeparator'))}} {{ t('subscription.concurrency') }} {{sub.access.maxConcurrent}} {{ t('subscription.requestsPerMinute') }} {{sub.access.requestsPerMinute}} {{ t('subscription.requests') }}</p><div class="actions"><el-button @click="openImport('subscribe',sub.service.publisher)">{{ t('subscription.updateService') }}</el-button><el-button @click="openImport('credential',sub.service.publisher)">{{ t('import.credentialTitle') }}</el-button><el-button type="danger" plain @click="removeSubscription(sub.service.publisher)">{{ t('subscription.remove') }}</el-button></div></el-card></section>
  <section v-if="page==='publisher'"><div class="toolbar"><p>{{ t('publisher.externalImportHint') }}</p><el-button type="primary" @click="openImport('install')">{{ t('publisher.install') }}</el-button></div><el-empty v-if="!state.saved.provider.service" :description="t('publisher.notInstalled')"/><el-card v-else><h3>{{ t('publisher.savedDelegation') }}</h3><p class="mono">{{state.saved.provider.service.publisher}}</p><p>{{ t('publisher.serviceIdLabel') }}{{state.saved.provider.service.id}}</p><p>{{ t('publisher.expiresLabel') }}{{date(state.saved.provider.service.expiresAt)}}</p><p>{{ t('publisher.modelsLabel') }}{{state.saved.provider.service.models?.join(t('common.listSeparator'))}}</p><p>{{ t('publisher.peersLabel') }}</p><p v-for="id in state.saved.provider.service.peers" :key="id" class="mono">{{id}}</p><el-divider/><el-alert v-if="state.revocationError" :title="state.revocationError" type="error" :closable="false"/><template v-else-if="state.revocations"><p>{{ t('revocations.sequenceLabel') }}{{state.revocations.sequence}} {{ t('revocations.validUntil') }} {{date(state.revocations.expiresAt)}}</p><p>{{ t('revocations.entriesLabel') }}{{state.revocations.revoked?.join(t('common.listSeparator'))||t('common.none')}}</p></template><el-button class="spaced" @click="openImport('apply-revocations',state.saved.provider.service.publisher)">{{ t('revocations.updateSigned') }}</el-button><p class="muted">{{ t('issuer.historyHint') }}</p></el-card></section>
  <section v-if="page==='models'"><el-alert :title="t('playground.quotaHint')" type="info" :closable="false"/><el-card class="spaced"><el-form label-position="top" @submit.prevent="chat"><el-form-item :label="t('playground.model')"><el-select v-model="model" filterable allow-create default-first-option class="full"><el-option v-for="m in models" :key="m.id" :label="m.id" :value="m.id"/></el-select></el-form-item><el-form-item :label="t('playground.prompt')"><el-input v-model="prompt" type="textarea" :rows="4" :disabled="streaming"/></el-form-item><el-button type="primary" native-type="submit" :disabled="streaming||!model||!prompt.trim()">{{ t('playground.send') }}</el-button><el-button v-if="streaming" @click="abort?.abort()">{{ t('playground.stop') }}</el-button></el-form><details v-if="reasoning"><summary>{{ t('playground.reasoning') }}</summary><pre>{{reasoning}}</pre></details><pre class="response" aria-live="polite">{{answer || (streaming?t('playground.waiting'):t('playground.empty'))}}</pre></el-card></section>
  <section v-if="page==='peers'"><el-empty v-if="!peers.length" :description="t('peers.empty')"/><el-card v-for="peer in peers" :key="peer.id" class="spaced"><h3>{{ t('peers.connected') }}</h3><p class="mono">{{peer.id}}</p><el-alert v-if="peer.error" :title="peer.error" type="warning" :closable="false"/><el-descriptions :column="1" border><el-descriptions-item :label="t('common.publisher')">{{peer.publisherId||t('common.notDeclared')}}</el-descriptions-item><el-descriptions-item :label="t('peers.paths')">{{peer.connectionPaths?.join(t('common.listSeparator'))||t('common.unknown')}}</el-descriptions-item><el-descriptions-item :label="t('peers.concurrency')">{{peer.maxConcurrent||t('common.unknown')}}</el-descriptions-item><el-descriptions-item :label="t('peers.models')">{{peer.models?.map((m:any)=>m.name).join(t('common.listSeparator'))||t('common.none')}}</el-descriptions-item></el-descriptions><details v-if="peer.reputation"><summary>{{ t('peers.reputation') }}</summary><pre>{{JSON.stringify(peer.reputation,null,2)}}</pre></details></el-card></section>
  <section v-if="page==='settings'"><div class="toolbar"><p>{{ t('config.editHint') }}</p><el-button type="primary" @click="drawer='settings'">{{ t('config.edit') }}</el-button></div><el-descriptions :column="1" border><el-descriptions-item :label="t('config.savedMode')">{{state.saved.network.mode}}</el-descriptions-item><el-descriptions-item :label="t('config.gatewayAddress')">{{state.saved.gateway.bindAddr}}</el-descriptions-item><el-descriptions-item :label="t('config.modelService')">{{state.saved.provider.enabled?t('common.enable'):t('common.close')}}</el-descriptions-item><el-descriptions-item :label="t('config.relayService')">{{state.saved.relay.enabled?t('common.enable'):t('common.close')}}</el-descriptions-item></el-descriptions><el-table :data="state.saved.backends" class="spaced"><el-table-column prop="name" :label="t('backend.name')"/><el-table-column prop="kind" :label="t('common.type')"/><el-table-column prop="baseUrl" :label="t('common.address')"/><el-table-column prop="enabled" :label="t('common.enable')"/></el-table></section>
  </template></el-main></el-container></el-container>
  <el-drawer :model-value="drawer==='settings'" :title="t('config.drawerTitle')" direction="rtl" size="var(--console-drawer-width)" destroy-on-close @close="drawer='' "><SettingsForm v-if="drawer==='settings'&&state" :config="state.saved" @save="value=>mutate('config','PUT',value)"/></el-drawer>
  <el-drawer :model-value="drawer==='import'" :title="guide.title" direction="rtl" size="var(--console-drawer-width)" destroy-on-close @close="drawer='' "><el-form label-position="top" @submit.prevent="importDocument"><div class="import-guide" data-test="import-guide"><p>{{guide.intro}}</p><ol><li v-for="(step,i) in guide.steps" :key="i">{{step}}</li></ol><div v-if="guide.issue.length&&authStatus"><el-button v-for="k in guide.issue" :key="k" size="small" @click="authStatus.openAssistant(k)">{{ISSUE_LABEL[k]}}</el-button></div></div><el-alert :title="t('import.verifyTrustNotice')" type="info" :closable="false" class="spaced"/><el-form-item :label="t('import.trustedPublisher')" required class="spaced"><el-input v-model="trust" :placeholder="t('import.publisherPlaceholder')"/><p class="field-hint">{{TRUST_HINT}}</p><p v-if="docPublisher" class="field-hint" data-test="publisher-compare">{{ t('import.signerLabel') }}<strong>{{docPublisher}}</strong>{{ t('common.period') }}<span v-if="!trust.trim()">{{ t('import.verifySignerHint') }}</span><span v-else-if="docPublisher===trust.trim()">{{ t('import.signerMatches') }}</span><span v-else class="hint-danger">{{ t('import.signerMismatch') }}</span></p></el-form-item><el-form-item :label="guide.documentLabel+t('common.requiredSuffix')" required><input type="file" accept=".json,.noobloft" @change="readDocument($event,'document')"/><el-input v-model="documentText" type="textarea" :rows="12" :placeholder="t('import.documentPlaceholder')"/><p class="field-hint">{{guide.document}}</p></el-form-item><el-form-item v-if="needsRevocations" :label="t('import.revocationsRequired')" required><input type="file" accept=".json" @change="readDocument($event,'revocations')"/><el-input v-model="revocationsText" type="textarea" :rows="7" :placeholder="t('import.revocationsPlaceholder')"/><p class="field-hint" data-test="revocations-hint">{{ t('revocations.explanation') }}<strong>{{ t('revocations.exampleCommand') }}</strong>{{ t('revocations.renewHint') }}</p></el-form-item><el-button native-type="submit" type="primary" :loading="busy" :disabled="!canImport">{{ t('import.validateSave') }}</el-button></el-form></el-drawer>
</template>
